# Generated by Django 2.0.6 on 2018-06-23 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('via', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='twitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twitter.Twitter'),
        ),
    ]
