# Generated by Django 2.0.6 on 2018-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electrical and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=1)),
                ('section', models.CharField(max_length=10)),
                ('subject_name1', models.CharField(max_length=50)),
                ('subject1_rating', models.IntegerField(default=0)),
                ('subject_name2', models.CharField(max_length=50)),
                ('subject2_rating', models.IntegerField(default=0)),
                ('subject_name3', models.CharField(max_length=50)),
                ('subject3_rating', models.IntegerField(default=0)),
                ('subject_name4', models.CharField(max_length=50)),
                ('subject4_rating', models.IntegerField(default=0)),
                ('subject_name5', models.CharField(max_length=50)),
                ('subject5_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=20)),
            ],
        ),
    ]
