# Generated by Django 2.0.6 on 2018-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electrical and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=1)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
