# Generated by Django 2.0.6 on 2018-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180811_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electrical and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=45),
        ),
    ]
