# Generated by Django 2.0.6 on 2018-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20180901_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30, null=True)),
                ('techer_dept', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Name',
            field=models.CharField(default='Rajat', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ratings',
            name='subject6_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='subject_name6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='teacher_name1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='teacher_name2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='teacher_name3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='teacher_name4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='teacher_name5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='teacher_name6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electrical and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='Computer Science', max_length=80),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='section',
            field=models.CharField(default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='subject_name1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='subject_name2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='subject_name3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='subject_name4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='subject_name5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
