# Generated by Django 2.0.6 on 2018-09-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20180901_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll_no', models.IntegerField(default='00', max_length=20, primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electrical and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='Computer Science', max_length=80)),
                ('section', models.CharField(default='S', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='Name',
        ),
        migrations.AddField(
            model_name='ratings',
            name='roll_no',
            field=models.IntegerField(default='00', max_length=20, primary_key=True, serialize=False),
        ),
    ]
