# Generated by Django 2.0.6 on 2018-09-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20180901_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='subject1_rating',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Audibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='Behaviour',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='Method_of_teaching',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='Punctuality',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='Subject_knowledge',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ratings',
            name='Syllabus_coverage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='roll_no',
            field=models.IntegerField(default='00', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default='00', primary_key=True, serialize=False),
        ),
    ]
