# Generated by Django 2.0.6 on 2018-09-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20180902_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='subject2_rating',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='subject3_rating',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='subject4_rating',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='subject5_rating',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='subject6_rating',
        ),
        migrations.AlterField(
            model_name='ratings',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electrical and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='Branch', max_length=80),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='section',
            field=models.CharField(default='Section', max_length=10),
        ),
    ]
