# Generated by Django 2.0.6 on 2018-07-09 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='text',
        ),
        migrations.AddField(
            model_name='teachers',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
